FROM libmesos/ubuntu
MAINTAINER ptorrestr <pablo.torres.t@gmail.com>
RUN curl -s http://www.apache.org/dist/hadoop/common/hadoop-2.4.1/hadoop-2.4.1.tar.gz | tar -xz -C /usr/local/
RUN cd /usr/local && ln -s ./hadoop-2.4.1 hadoop
